# Generated by Django 4.1.2 on 2023-12-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_delete_auto_delete_comuna_delete_estacionamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_cliente',
        ),
    ]
