# Generated by Django 4.1.2 on 2023-12-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
