# Generated by Django 4.1.2 on 2023-12-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estacionamiento',
        ),
    ]
