# Generated by Django 4.1.2 on 2023-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComuna', models.CharField(max_length=80)),
                ('imagenComuna', models.ImageField(null=True, upload_to='comunas')),
            ],
        ),
    ]
