# Generated by Django 4.1.2 on 2023-11-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comuna',
            table='Comuna',
        ),
    ]
