# Generated by Django 4.1.2 on 2023-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunas', '0002_alter_comuna_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='imagenComuna',
            field=models.ImageField(null=True, upload_to='', verbose_name='images/'),
        ),
    ]
