# Generated by Django 4.1.2 on 2023-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunas', '0003_alter_comuna_imagencomuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='imagenComuna',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
