# Generated by Django 4.1.2 on 2023-12-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Usuario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TipoUsuario',
            },
        ),
    ]
